/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import objects.MyBean;
import objects.MyTableModel;
import passwordholder2.PasswordHolder2;
import static passwordholder2.PasswordHolder2.beans;
import utils.FileUtils;

/**
 *
 * @author Toshiba
 */
public class MainForm extends javax.swing.JFrame {

    /**
     * Creates new form MainForm
     */
    public MainForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        tfWhereFrom = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tfLogin = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tfPassword = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tfOptions = new javax.swing.JTextField();
        btnAddtoTable = new javax.swing.JButton();
        btnSaveToFile = new javax.swing.JButton();
        btnDeleteFromTable = new javax.swing.JButton();
        spinnerCount = new javax.swing.JSpinner();
        jButton4 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel1MouseClicked(evt);
            }
        });

        tfWhereFrom.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        tfWhereFrom.setForeground(new java.awt.Color(204, 204, 204));
        tfWhereFrom.setText("Имя сервиса");
        tfWhereFrom.setToolTipText("От чего логин");
        tfWhereFrom.setName("tfWhereFrom"); // NOI18N
        tfWhereFrom.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfWhereFromFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfWhereFromFocusLost(evt);
            }
        });

        jLabel1.setText("Сайт/сервис");

        jLabel2.setText("Логин");

        tfLogin.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        tfLogin.setForeground(new java.awt.Color(204, 204, 204));
        tfLogin.setText("Логин");
        tfLogin.setName("tfLogin"); // NOI18N
        tfLogin.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfLoginFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfLoginFocusLost(evt);
            }
        });

        jLabel3.setText("Пароль");

        tfPassword.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        tfPassword.setForeground(new java.awt.Color(204, 204, 204));
        tfPassword.setText("Пароль");
        tfPassword.setToolTipText("Пароль");
        tfPassword.setName("tfPassword"); // NOI18N
        tfPassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfPasswordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfPasswordFocusLost(evt);
            }
        });

        jLabel4.setText("Дополнительно");

        tfOptions.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        tfOptions.setForeground(new java.awt.Color(204, 204, 204));
        tfOptions.setText("Дополнительно");
        tfOptions.setName("tfOptions"); // NOI18N
        tfOptions.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfOptionsFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfOptionsFocusLost(evt);
            }
        });

        btnAddtoTable.setText("Изменить/Добавить запись");
        btnAddtoTable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddtoTableActionPerformed(evt);
            }
        });

        btnSaveToFile.setText("СОХРАНИТЬ В ФАЙЛ");
        btnSaveToFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveToFileActionPerformed(evt);
            }
        });

        btnDeleteFromTable.setText("Удалить запись");
        btnDeleteFromTable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteFromTableActionPerformed(evt);
            }
        });

        spinnerCount.setToolTipText("Количество символов в пароле");
        spinnerCount.setValue(8);

        jButton4.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jButton4.setText("Сгенерировать");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Password holder v1");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAddtoTable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSaveToFile, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDeleteFromTable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(tfPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(spinnerCount, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton4))
                                    .addComponent(tfLogin)
                                    .addComponent(tfWhereFrom)
                                    .addComponent(tfOptions))))
                        .addGap(0, 13, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfWhereFrom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tfPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spinnerCount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tfOptions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAddtoTable)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDeleteFromTable)
                .addGap(39, 39, 39)
                .addComponent(btnSaveToFile, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTable2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTable2.setModel(new MyTableModel());
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 848, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tfWhereFromFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfWhereFromFocusGained
        GUIUtils.focusGained((JTextField) evt.getComponent());
        // TODO add your handling code here:
    }//GEN-LAST:event_tfWhereFromFocusGained

    private void tfLoginFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfLoginFocusGained
 GUIUtils.focusGained((JTextField) evt.getComponent());
    }//GEN-LAST:event_tfLoginFocusGained

    private void tfPasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfPasswordFocusGained
        // TODO add your handling code here:
         GUIUtils.focusGained((JTextField) evt.getComponent());
    }//GEN-LAST:event_tfPasswordFocusGained

    private void tfOptionsFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfOptionsFocusGained
        // TODO add your handling code here:
         GUIUtils.focusGained((JTextField) evt.getComponent());
    }//GEN-LAST:event_tfOptionsFocusGained

    private void tfWhereFromFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfWhereFromFocusLost
        // TODO add your handling code here:
        GUIUtils.focusLost((JTextField) evt.getComponent());
    }//GEN-LAST:event_tfWhereFromFocusLost

    private void tfLoginFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfLoginFocusLost
        // TODO add your handling code here:
        GUIUtils.focusLost((JTextField) evt.getComponent());
    }//GEN-LAST:event_tfLoginFocusLost

    private void tfPasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfPasswordFocusLost
        // TODO add your handling code here:
        GUIUtils.focusLost((JTextField) evt.getComponent());
    }//GEN-LAST:event_tfPasswordFocusLost

    private void tfOptionsFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfOptionsFocusLost
        // TODO add your handling code here:
        GUIUtils.focusLost((JTextField) evt.getComponent());
    }//GEN-LAST:event_tfOptionsFocusLost

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        int count = (int) spinnerCount.getValue();
        String pass = GUIUtils.passwordGenerator(count);
        GUIUtils.writeTextField(tfPassword, pass);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void btnDeleteFromTableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteFromTableActionPerformed
        // TODO add your handling code here:
        
        
        int tmp = jTable2.getSelectedRow();
        if(tmp==0){
            
        }
        else{
        PasswordHolder2.beans.remove(tmp);
        jTable2.updateUI();}
                
    }//GEN-LAST:event_btnDeleteFromTableActionPerformed

    private void btnAddtoTableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddtoTableActionPerformed
        // TODO add your handling code here:
        if(!tfWhereFrom.getText().equals("Имя сервиса")){
        
        String tmp=tfOptions.getText();
         if(tmp.equals("Дополнительно")){
             tmp="";
         }
         boolean isChangeble=false;
        for(MyBean b :beans){
            if(b.getWhereFrom().equals(tfWhereFrom.getText())){
                if(b.getLogin().equals(tfLogin.getText())){
                    b.setPassword(tfPassword.getText());
                    if(!tmp.equals("")){
                    b.setOptions(tmp);}
                    isChangeble=true;
                }
            }
        }
       
        if(!isChangeble){
        beans.add(new MyBean(tfWhereFrom.getText(), tfLogin.getText(),tfPassword.getText(),tmp));}
        jTable2.updateUI();
            GUIUtils.writeDefaultTextField(tfWhereFrom);
            GUIUtils.writeDefaultTextField(tfLogin);
            GUIUtils.writeDefaultTextField(tfPassword);
            GUIUtils.writeDefaultTextField(tfOptions);
        
}
    }//GEN-LAST:event_btnAddtoTableActionPerformed

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        // TODO add your handling code here:
        int tmp = jTable2.getSelectedRow();
        MyBean bean = beans.get(tmp);
        GUIUtils.writeTextField(tfWhereFrom, bean.getWhereFrom());
        GUIUtils.writeTextField(tfLogin, bean.getLogin());
        GUIUtils.writeTextField(tfPassword, bean.getPassword());
        GUIUtils.writeTextField(tfOptions, bean.getOptions());
                
    }//GEN-LAST:event_jTable2MouseClicked

    private void jPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseClicked
        // TODO add your handling code here:
         GUIUtils.writeDefaultTextField(tfWhereFrom);
            GUIUtils.writeDefaultTextField(tfLogin);
            GUIUtils.writeDefaultTextField(tfPassword);
            GUIUtils.writeDefaultTextField(tfOptions);
    }//GEN-LAST:event_jPanel1MouseClicked

    private void btnSaveToFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveToFileActionPerformed
        try {
            // TODO add your handling code here:
            FileUtils.writeToFile();
            JOptionPane.showMessageDialog(this,"Сохранил");
        } catch (FileNotFoundException ex) {
            Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this,"Ошибка при сохранении файла");
        } catch (IOException ex) {
            Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        
      
    }//GEN-LAST:event_btnSaveToFileActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddtoTable;
    private javax.swing.JButton btnDeleteFromTable;
    private javax.swing.JButton btnSaveToFile;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    private javax.swing.JSpinner spinnerCount;
    private javax.swing.JTextField tfLogin;
    private javax.swing.JTextField tfOptions;
    private javax.swing.JTextField tfPassword;
    private javax.swing.JTextField tfWhereFrom;
    // End of variables declaration//GEN-END:variables
}
